version: '3'
services:
  api:
    build: ./server
    restart: always
    expose:
      - "8080"
    volumes:
      - ./server/hm.db:/app/hm.db
      - ./server/public:/app/public
  nginx:
    build: ./viewer
    restart: always
    links:
      - api
    ports:
      - "8080:80"
